
version: 2

seed: 0

installTo: C:\Program Files (x86)\Steam\steamapps\common\Trials of Mana
pakName: TypesOfMania_P

# these are the base stats
# they will be applied to all creatures without something set
# so, if you set boss.hp = 3, this won't override that
# but if you don't set boss.def, this will set it to 1
base:

  # core stats
  hp: 2
  mp: 1
  atk: 1.5
  def: 1
  agi: 1
  int: 1
  spr: 1
  luck: 1

  # possibly related to enemy magic offense/defense, since most of them don't have agi/int/spr set
  defMag: 1.3
  offMag: 1.3

  # possibly related to the durability of break bars/guards
  downDurable: 1
  guardDurable: 1

  # drop-related stats
  exp: 0.8
  lucre: 1

  # item drop rates (monsters can only drop up to 3 items. #1 is always more common than #2, and so on)
  drop1: 1
  drop2: 1
  drop3: 1

  # spp related rates (the amount of skill power dropped when certain conditions happen)
  # if someone could tell me the specific cases these all trigger, that would be helpful!
  dropSpp: 1
  knockoutDropSpp: 1
  lAttackDropSpp: 1
  chargeAttackDropSpp: 1

# boss-specific overrides go here
boss:

# normal enemy-specific overrides go here
monster:

# shinju-specific overrides go here
shinju:

# part-specific overrides go here
part:

# specific monster overrides go here
specific:
